#사용할 변수
varialbles:
# 백엔드가 동작할 포트
  port: 8060

  #feurl
  feUri: http://localhost:3060

  #리다이렉트할때 쓸 url
  beUri: http://localhost:${varialbles.port}
  value: local

#여기서부터 설정파일
server:
  port: ${varialbles.port}
  servlet:
    session:
      timeout: 500m      # 60m * 24h * 30d
      cookie:
        max-age: 500m    # 60m * 24h * 30d
        name: SID
        http-only: true
        secure: true

spring:
  profiles:
    active:
      - local
  datasource:
    url: jdbc:mysql://localhost:3306/jobterview?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        format_sql: true #쿼리 포맷팅 활성화

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 682444755899-3eqgd34dqavn8mq0us3q4e0lf09pbc4v.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: ${varialbles.beUri}/login/oauth2/code/google
            scope:
              - email
              - profile

          kakao:
            client-id: f8ae067dc6798972969cd650aca79d01
            client-secret: u8FZ07hOCRzzLlr2QbVgHVnp5MeCSSuo
            redirect-uri: ${varialbles.beUri}/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging.level:
  org.hibernate.SQL: info

mail:
  smtp:
    timeout: 5000
    auth: true
    starttls:
      required: true
      enable: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465
    port: 465
    host: smtp.gmail.com

AdminMail:
  id: jobterview1@gmail.com
  password: onzkacghyhqoznpq

servlet:
  session:
    timeout: 300m